version: "3"
services:
  db:
    container_name: postgres
    image: "postgres:latest"
    environment:
      POSTGRES_USER: david_prod
      POSTGRES_PASSWORD: david_pwd_prod
    volumes:
      - ./dbData:/var/lib/postgresql

  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  api:
    container_name: api
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on: 
      - db
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://david_prod:david_pwd_prod@db:5432/db_dev?schema=public"
    volumes:
      - /app/node_modules
      - /app/prisma

  client:
    container_name: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - /app/.next

volumes:
  db: