version: "3"
services:
  db:
    container_name: postgres
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_USER: david_dev
      POSTGRES_PASSWORD: david_pwd_dev
    volumes:
      - ./db:/var/lib/postgresql
  adminer:
    image: adminer
    depends_on: 
      - db
    restart: always
    ports:
      - 8080:8080
  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - ./server:/app
    environment:
      POSTGRES_USER: david_dev
      POSTGRES_PASSWORD: david_pwd_dev
      PGHOST: db
      PGDATABASE: db_dev
      PGPORT: 5432
  client:
    container_name: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app