version: "3"
services:
  db:
    container_name: postgres
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_USER: david_dev
      POSTGRES_PASSWORD: david_pwd_dev
  
  prisma:
    links:
      - db
    depends_on:
      - db
    container_name: prisma
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: "postgresql://david_dev:david_pwd_dev@db:5432/db_dev?schema=public"
    build:
      context: server/prisma
      dockerfile: Dockerfile.dev
  
  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  
  api:
    container_name: api
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    depends_on: 
      - db
    volumes:
      - ./server:/app

  client:
    container_name: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app