version: "3"
services:
  db:
    container_name: postgres
    image: "postgres:latest"
    environment:
      POSTGRES_USER: david_prod
      POSTGRES_PASSWORD: david_pwd_prod
      POSTGRES_DB: db_prod
    volumes:
      - ./db:/var/lib/postgresql*

  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: "./server"
    environment:
      POSTGRES_USER: david_prod
      POSTGRES_PASSWORD: david_pwd_prod
      PGHOST: db
      POSTGRES_DB: db_prod
      PGPORT: 5432
      
  client:
    container_name: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client