services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080