version: "3"
services:
  db:
    container_name: postgres_dev
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: david_pwd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"

  api:
    container_name: api_dev
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./server:/app

  client:
    container_name: client_dev
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
